"""
https://projecteuler.net/problem=2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
def fibonacci(n):
    """calculate fibonacci number"""
    fibonacciN_1 = 2
    fibonacciN_2 = 1
    if n == 1:
        return 1
    elif n == 2:
        return 2
    else:
        for i in range(3,n+1):
            fibonacciN = fibonacciN_1+fibonacciN_2
            fibonacciN_2 = fibonacciN_1
            fibonacciN_1 = fibonacciN
    return fibonacciN
def main():
    i = 1
    sum = 0
    while fibonacci(i) < 4000000:
        if fibonacci(i)%2 == 0:
            sum += fibonacci(i)
        i += 1
    print(sum)

if __name__ == '__main__':
    main()
	